export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:response', async (response, { event }) => {
    if (response.statusCode !== 404) return;

    const slug = event.path.split('/').find(Boolean);
    if (!slug) return;

    // Nitro uses /\W/g to normalize cache keys (removes non-word characters),
    // so "igor-oliveira" → "igoroliveira" but "renato_cron" → "renato_cron"
    // Source: nitropack/dist/runtime/internal/cache.mjs line 125
    const normalizedSlug = slug.replace(/\W/g, '');

    try {
      // hubKV is a Nitro auto-import from @nuxthub/core — types generated by nuxt prepare
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-expect-error
      const kv = hubKV();
      const keys = await kv.keys(`nitro:routes:_:${normalizedSlug}`);
      await Promise.all(keys.map((key: string) => kv.removeItem(key)));
    } catch (err) {
      console.error(
        `[purge-stale-on-404] Failed to purge KV for slug "${slug}":`,
        err,
      );
    }
  });
});
